#!/usr/bin/env python3
"""
Varre src/icons/new-sessao-atual/ e produz catalog.json com descrição de cada SVG.

Heurística:
- Descrição em PT-BR derivada do nome do arquivo
- Tags categóricas baseadas em dicionário temático
- Cores predominantes extraídas do SVG (via regex)
- Tamanho em bytes
"""

from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FONTE = REPO / "src" / "icons" / "new-sessao-atual"
SAIDA = REPO / "catalog.json"

TRADUCOES_PT = {
    # Genéricos do cotidiano
    "air-hockey": "mesa de air hockey",
    "alien": "alienígena",
    "alien-variant": "alienígena (variação)",
    "amphora": "ânfora antiga",
    "aphrodite": "deusa Afrodite",
    "arcade": "máquina de arcade",
    "asteroid": "asteroide",
    "astronaut": "astronauta",
    "athena": "deusa Atena",
    "axe": "machado",
    "bag": "bolsa",
    "balloon": "balão",
    "balloons": "balões",
    "bat": "morcego",
    "bats": "morcegos",
    "bible": "bíblia",
    "billiard": "bola de sinuca",
    "black-cat": "gato preto",
    "blood-transfusion": "transfusão de sangue",
    "bomb": "bomba",
    "bones": "ossos",
    "book": "livro",
    "books": "livros",
    "box": "caixa",
    "brain": "cérebro",
    "broken": "quebrado",
    "broom": "vassoura",
    "broomstick": "cabo de vassoura",
    "bucket": "balde",
    "bug": "inseto",
    "building": "edifício",
    "candies": "doces",
    "candies-variant": "doces (variação)",
    "candle": "vela",
    "candle-variant": "vela (variação)",
    "candles": "velas",
    "candlestick": "castiçal",
    "candy-cane": "bengala doce",
    "candy-corn": "milho doce",
    "capsule": "cápsula",
    "cards": "baralho",
    "cards-variant": "baralho (variação)",
    "castle": "castelo",
    "cat": "gato",
    "cauldron": "caldeirão",
    "cemetery": "cemitério",
    "centaur": "centauro",
    "chariot": "carruagem",
    "chess": "xadrez",
    "chest": "baú",
    "chest-variant": "baú (variação)",
    "chips": "fichas",
    "circle": "círculo",
    "cleaver": "cutelo",
    "clown": "palhaço",
    "coffin": "caixão",
    "column": "coluna grega",
    "computer": "computador",
    "computer-game": "videogame",
    "console": "console",
    "constellation": "constelação",
    "corpse": "cadáver",
    "costume": "fantasia",
    "cross": "cruz",
    "crow": "corvo",
    "crown": "coroa",
    "crystal": "cristal",
    "crystal-ball": "bola de cristal",
    "cupcake": "cupcake",
    "cyclops": "ciclope",
    "dagger": "adaga",
    "darts": "dardos",
    "dead-tree": "árvore morta",
    "dessert": "sobremesa",
    "devil": "demônio",
    "dice": "dados",
    "domino": "dominó",
    "dove": "pomba",
    "dracula": "Drácula",
    "dracula-hex": "hexágono Dracula",
    "dwarf": "anão",
    "earth": "Terra",
    "eclipse": "eclipse",
    "enchanted-mirror": "espelho encantado",
    "evil": "mal",
    "eye": "olho",
    "eye-ball": "globo ocular",
    "eyeball": "globo ocular (variação)",
    "fairy": "fada",
    "fairy-dust": "pó de fada",
    "fangs": "presas",
    "fear": "medo",
    "feather": "pena",
    "finger": "dedo",
    "fire": "fogo",
    "flag": "bandeira",
    "flask": "frasco",
    "food": "comida",
    "fortune-telling": "adivinhação",
    "frankenstein": "Frankenstein",
    "full-moon": "lua cheia",
    "galaxy": "galáxia",
    "galaxy-variant": "galáxia (variação)",
    "gallows": "forca",
    "game-controller": "controle de videogame",
    "gameboy": "Game Boy",
    "gaming": "games",
    "gate": "portão",
    "gemstone": "gema",
    "genie": "gênio",
    "ghost": "fantasma",
    "ghost-variant": "fantasma (variação)",
    "ghosts": "fantasmas",
    "gift": "presente",
    "gifts": "presentes",
    "globe": "globo",
    "glove": "luva",
    "grapes": "uvas",
    "grave": "túmulo",
    "grave-variant": "túmulo (variação)",
    "graveyard": "cemitério",
    "graveyard-variant": "cemitério (variação)",
    "griffin": "grifo",
    "grim-reaper": "ceifador",
    "guillotine": "guilhotina",
    "halloween": "halloween",
    "halloween-variant": "halloween (variação)",
    "hand": "mão",
    "handcuff": "algema",
    "handcuffs": "algemas",
    "harp": "harpa",
    "haunted-house": "casa mal-assombrada",
    "hearts": "corações",
    "hephaestus": "deus Hefesto",
    "hephaestus-variant": "Hefesto (variação)",
    "hermes": "deus Hermes",
    "hermes-variant": "Hermes (variação)",
    "hook": "gancho",
    "hourglass": "ampulheta",
    "hydra": "hidra",
    "jack-o-lantern": "abóbora iluminada",
    "jenga": "torre Jenga",
    "kappa": "kappa (criatura)",
    "key": "chave",
    "knife": "faca",
    "kraken": "kraken",
    "lantern": "lanterna",
    "laurel": "coroa de louros",
    "living-dead": "morto-vivo",
    "lollipop": "pirulito",
    "lyre": "lira",
    "magic": "magia",
    "magic-assistant": "assistente mágico",
    "magic-ball": "bola mágica",
    "magic-broom": "vassoura mágica",
    "magic-cape": "capa mágica",
    "magic-hat": "chapéu mágico",
    "magic-lamp": "lâmpada mágica",
    "magic-mirror": "espelho mágico",
    "magic-trick": "truque de mágica",
    "magic-trick-variant": "truque (variação)",
    "magic-wand": "varinha mágica",
    "magic-wand-variant": "varinha (variação)",
    "magician": "mágico",
    "magician-hat": "cartola mágica",
    "magician-hat-variant": "cartola (variação)",
    "makeup": "maquiagem",
    "mandolin": "bandolim",
    "mask": "máscara",
    "mask-variant": "máscara (variação)",
    "mass": "massa",
    "meteor": "meteoro",
    "minotaur": "minotauro",
    "mobile-game": "jogo mobile",
    "monkey": "macaco",
    "monster": "monstro",
    "monster-variant": "monstro (variação)",
    "moon": "lua",
    "mortar": "almofariz",
    "mouse": "rato",
    "muffin": "muffin",
    "mummy": "múmia",
    "mushroom": "cogumelo",
    "night": "noite",
    "observatory": "observatório",
    "owl": "coruja",
    "padlock": "cadeado",
    "paper-bag": "saco de papel",
    "parthenon": "Partenon",
    "party": "festa",
    "pendant": "pingente",
    "phoenix": "fênix",
    "pirate": "pirata",
    "planet": "planeta",
    "planet-variant": "planeta (variação)",
    "planet-variant-two": "planeta (variação 2)",
    "plant": "planta",
    "podium": "pódio",
    "poison": "veneno",
    "pot": "pote",
    "potion": "poção",
    "potion-variant": "poção (variação)",
    "powder": "pó",
    "prisoner": "prisioneiro",
    "pumpkin": "abóbora",
    "pumpkin-variant": "abóbora (variação)",
    "pumpkins": "abóboras",
    "puzzle": "quebra-cabeça",
    "rabbit": "coelho",
    "rainbow": "arco-íris",
    "reaper": "ceifador",
    "ring": "anel",
    "robot": "robô",
    "robot-variant": "robô (variação)",
    "robot-variant-two": "robô (variação 2)",
    "rocket": "foguete",
    "roulette": "roleta",
    "rum": "rum",
    "sandglass": "ampulheta de areia",
    "satellite": "satélite",
    "satellite-dish": "antena parabólica",
    "satellite-variant": "satélite (variação)",
    "satellite-variant-two": "satélite (variação 2)",
    "satellite-variant-three": "satélite (variação 3)",
    "saw": "serra",
    "scarecrow": "espantalho",
    "scream": "grito",
    "scroll": "pergaminho",
    "scythe": "foice",
    "serial-killer": "serial killer",
    "shield": "escudo",
    "skeleton": "esqueleto",
    "skeleton-variant": "esqueleto (variação)",
    "skull": "caveira",
    "slot-machine": "caça-níqueis",
    "smoke": "fumaça",
    "snake": "cobra",
    "space": "espaço",
    "space-capsule": "cápsula espacial",
    "spaceship": "nave espacial",
    "spell": "feitiço",
    "spell-book": "livro de feitiços",
    "spell-variant": "feitiço (variação)",
    "spellbook": "grimório",
    "spider": "aranha",
    "spider-web": "teia de aranha",
    "stage": "palco",
    "sun": "sol",
    "sweets": "doces",
    "sword": "espada",
    "target": "alvo",
    "tarot": "tarô",
    "telescope": "telescópio",
    "tent": "tenda",
    "tetris": "tetris",
    "tetris-variant": "tetris (variação)",
    "three-dimensional-glasses": "óculos 3D",
    "tic-tac-toe": "jogo da velha",
    "ticket": "ingresso",
    "tombstone": "lápide",
    "tombstone-variant": "lápide (variação)",
    "toolbox": "caixa de ferramentas",
    "torch": "tocha",
    "treasure-chest": "baú de tesouro",
    "tree": "árvore",
    "trick": "truque",
    "trident": "tridente",
    "trireme": "trirreme",
    "tube": "tubo",
    "unicorn": "unicórnio",
    "vampire": "vampiro",
    "vial": "frasco de ensaio",
    "video-card": "placa de vídeo",
    "violin": "violino",
    "virtual-reality": "realidade virtual",
    "voodoo": "vodu",
    "voodoo-doll": "boneco de vodu",
    "wand": "varinha",
    "werewolf": "lobisomem",
    "winner": "vencedor",
    "witch": "bruxa",
    "witch-hat": "chapéu de bruxa",
    "witch-variant": "bruxa (variação)",
    "wizard": "mago",
    "wizard-hat": "chapéu de mago",
    "wizard-variant": "mago (variação)",
    "zeus": "deus Zeus",
    "zombie": "zumbi",
    "zombie-variant": "zumbi (variação)",
}

CATEGORIAS = {
    "gotico": {
        "bat", "bats", "black-cat", "coffin", "corpse", "crow", "dead-tree",
        "dracula", "dracula-hex", "fangs", "frankenstein", "ghost", "ghost-variant",
        "ghosts", "grave", "grave-variant", "graveyard", "graveyard-variant",
        "grim-reaper", "haunted-house", "living-dead", "mummy", "reaper",
        "scarecrow", "serial-killer", "skeleton", "skeleton-variant", "skull",
        "spider", "spider-web", "tombstone", "tombstone-variant", "vampire",
        "werewolf", "witch", "witch-hat", "witch-variant", "zombie",
        "zombie-variant", "evil", "devil", "monster", "monster-variant",
    },
    "mitologia": {
        "amphora", "aphrodite", "athena", "centaur", "chariot", "column",
        "cyclops", "hephaestus", "hephaestus-variant", "hermes",
        "hermes-variant", "hydra", "kraken", "laurel", "minotaur", "parthenon",
        "phoenix", "trireme", "zeus", "griffin",
    },
    "fantasia_magia": {
        "cauldron", "crystal-ball", "crystal", "enchanted-mirror", "fairy",
        "fairy-dust", "fortune-telling", "genie", "magic", "magic-assistant",
        "magic-ball", "magic-broom", "magic-cape", "magic-hat", "magic-lamp",
        "magic-mirror", "magic-trick", "magic-trick-variant", "magic-wand",
        "magic-wand-variant", "magician", "magician-hat",
        "magician-hat-variant", "potion", "potion-variant", "spell",
        "spell-book", "spell-variant", "spellbook", "tarot", "unicorn", "wand",
        "wizard", "wizard-hat", "wizard-variant", "voodoo", "voodoo-doll",
    },
    "espaco_scifi": {
        "alien", "alien-variant", "asteroid", "astronaut", "earth", "eclipse",
        "galaxy", "galaxy-variant", "meteor", "moon", "full-moon",
        "observatory", "planet", "planet-variant", "planet-variant-two",
        "rocket", "satellite", "satellite-dish", "satellite-variant",
        "satellite-variant-two", "satellite-variant-three", "space",
        "space-capsule", "spaceship", "sun", "telescope", "constellation",
        "robot", "robot-variant", "robot-variant-two", "virtual-reality",
        "three-dimensional-glasses",
    },
    "jogos": {
        "air-hockey", "arcade", "billiard", "cards", "cards-variant", "chess",
        "chips", "console", "darts", "dice", "domino", "game-controller",
        "gameboy", "gaming", "jenga", "mobile-game", "computer-game",
        "roulette", "slot-machine", "tetris", "tetris-variant", "tic-tac-toe",
        "ticket", "podium", "stage", "puzzle", "winner",
    },
    "objetos_ferramentas": {
        "axe", "bag", "box", "broom", "broomstick", "bucket", "chest",
        "chest-variant", "cleaver", "dagger", "flask", "gallows", "gate",
        "glove", "guillotine", "handcuff", "handcuffs", "hook", "key",
        "knife", "lantern", "padlock", "paper-bag", "pot", "saw", "scythe",
        "shield", "sword", "target", "tent", "toolbox", "torch",
        "treasure-chest", "trident", "tube", "vial",
    },
    "halloween_doces": {
        "candies", "candies-variant", "candle", "candle-variant", "candles",
        "candlestick", "candy-cane", "candy-corn", "costume", "cupcake",
        "dessert", "food", "gift", "gifts", "halloween", "halloween-variant",
        "jack-o-lantern", "lollipop", "mask", "mask-variant", "muffin",
        "party", "pumpkin", "pumpkin-variant", "pumpkins", "sweets",
        "trick",
    },
    "utilitarios_conceitos": {
        "bible", "book", "books", "bomb", "bones", "brain", "broken",
        "bug", "building", "castle", "cemetery", "circle", "clown", "computer",
        "cross", "crown", "dwarf", "eye", "eye-ball", "eyeball", "fear",
        "feather", "finger", "fire", "flag", "gemstone", "globe", "grapes",
        "hand", "hearts", "hourglass", "kappa", "mandolin", "mass", "monkey",
        "mortar", "mouse", "mushroom", "night", "owl", "pendant", "pirate",
        "plant", "powder", "prisoner", "rabbit", "rainbow", "ring",
        "rum", "sandglass", "scream", "scroll", "smoke", "snake",
        "cat", "balloon", "balloons", "blood-transfusion", "capsule",
        "dove", "harp", "lyre", "makeup", "poison", "violin", "video-card",
        "tree",
    },
}


def categorizar(nome: str) -> list[str]:
    tags = []
    for cat, nomes in CATEGORIAS.items():
        if nome in nomes:
            tags.append(cat)
    if not tags:
        tags.append("outros")
    return tags


def cores_dominantes(svg_path: Path, top_n: int = 5) -> list[str]:
    try:
        texto = svg_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return []
    cores = re.findall(r"#[0-9a-fA-F]{6}|#[0-9a-fA-F]{3}", texto)
    cores_lower = [c.lower() for c in cores]
    mais_comuns = Counter(cores_lower).most_common(top_n)
    return [c for c, _ in mais_comuns]


def main() -> None:
    catalog: dict[str, dict] = {}
    total = 0
    sem_trad = []

    for svg in sorted(FONTE.glob("*.svg")):
        nome = svg.stem
        descricao = TRADUCOES_PT.get(nome, nome.replace("-", " "))
        if nome not in TRADUCOES_PT:
            sem_trad.append(nome)
        catalog[svg.name] = {
            "nome": nome,
            "descricao": descricao,
            "tags": categorizar(nome),
            "cores_dominantes": cores_dominantes(svg),
            "tamanho_bytes": svg.stat().st_size,
        }
        total += 1

    SAIDA.write_text(json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True))
    print(f"Catalogados: {total} SVGs")
    print(f"Sem traducao PT-BR: {len(sem_trad)}")
    if sem_trad:
        print(f"  {', '.join(sem_trad[:10])}{'...' if len(sem_trad) > 10 else ''}")
    print(f"Arquivo gerado: {SAIDA}")


if __name__ == "__main__":
    main()

# "A arte de conhecer é a arte de distinguir." -- Seneca
